/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BoardCodeRouteImport } from './routes/$boardCode'
import { Route as IndexRouteImport } from './routes/index'

const BoardCodeRoute = BoardCodeRouteImport.update({
  id: '/$boardCode',
  path: '/$boardCode',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$boardCode': typeof BoardCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$boardCode': typeof BoardCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$boardCode': typeof BoardCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$boardCode'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$boardCode'
  id: '__root__' | '/' | '/$boardCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardCodeRoute: typeof BoardCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$boardCode': {
      id: '/$boardCode'
      path: '/$boardCode'
      fullPath: '/$boardCode'
      preLoaderRoute: typeof BoardCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardCodeRoute: BoardCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
